//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gruppBNY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int category_Id { get; set; }
        public string type_of_competence { get; set; }
        public Nullable<int> competence_id { get; set; }
    
        public virtual competence competence { get; set; }
    }
}
