//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gruppBNY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_history
    {
        public int work_Id { get; set; }
        public string company { get; set; }
        public string work_position { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string work_duties { get; set; }
        public Nullable<int> freelancer_id { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
    }
}
